
services:
  - type: web
    name: educational-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: educational-platform-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: educational-platform-db
    databaseName: educational_platform
    user: ahmed_helly
